#!/usr/bin/env bash
# Provision (or refresh) WordPress credentials for Maestro E2E on local WordPress Studio.
#
# Creates maestro-e2e user + application password via `studio wp`, writes expo/.maestro/.env,
# and verifies against POST /wp-json/complex-patient/v1/auth/exchange.
#
# Usage:
#   bash scripts/maestro-provision-wp-user.sh
#   bash scripts/maestro-provision-wp-user.sh --verify-only
#
# Environment overrides:
#   COMPLEX_PATIENT_STUDIO_SITE_PATH  default: ~/Studio/the-complex-patient
#   COMPLEX_PATIENT_LOCAL_WP_URL      default: http://localhost:8881
#   MAESTRO_WP_USERNAME               default: maestro-e2e
#   MAESTRO_VAULT_PASSPHRASE          preserved from .env or default test phrase
#   MAESTRO_APP_PASSWORD_NAME         default: Maestro local
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.maestro/.env"
ENV_EXAMPLE="$ROOT/.maestro/.env.example"

STUDIO_SITE_PATH="${COMPLEX_PATIENT_STUDIO_SITE_PATH:-$HOME/Studio/the-complex-patient}"
LOCAL_WP_URL="${COMPLEX_PATIENT_LOCAL_WP_URL:-http://localhost:8881}"
WP_USER="${MAESTRO_WP_USERNAME:-maestro-e2e}"
APP_PASSWORD_NAME="${MAESTRO_APP_PASSWORD_NAME:-Maestro local}"
DEFAULT_VAULT_PASSPHRASE="${MAESTRO_VAULT_PASSPHRASE:-MaestroTestVaultPhrase2026!}"
BIRTH_MONTH="${MAESTRO_BIRTH_MONTH:-6}"
BIRTH_YEAR="${MAESTRO_BIRTH_YEAR:-1990}"

VERIFY_ONLY=false
NO_VERIFY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --verify-only)
      VERIFY_ONLY=true
      ;;
    --no-verify)
      NO_VERIFY=true
      ;;
    -h | --help)
      sed -n '1,20p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
  shift
done

read_env_value() {
  local key="$1"
  local file="$2"
  [[ -f "$file" ]] || return 0
  local line
  line="$(grep -E "^${key}=" "$file" 2>/dev/null | tail -n 1 || true)"
  [[ -n "$line" ]] || return 0
  printf '%s' "${line#*=}"
}

load_existing_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    return 0
  fi
  local saved_passphrase saved_month saved_year saved_user
  saved_passphrase="$(read_env_value MAESTRO_VAULT_PASSPHRASE "$ENV_FILE")"
  saved_month="$(read_env_value MAESTRO_BIRTH_MONTH "$ENV_FILE")"
  saved_year="$(read_env_value MAESTRO_BIRTH_YEAR "$ENV_FILE")"
  saved_user="$(read_env_value MAESTRO_WP_USERNAME "$ENV_FILE")"
  [[ -n "$saved_passphrase" ]] && DEFAULT_VAULT_PASSPHRASE="$saved_passphrase"
  [[ -n "$saved_month" ]] && BIRTH_MONTH="$saved_month"
  [[ -n "$saved_year" ]] && BIRTH_YEAR="$saved_year"
  # Ignore placeholder usernames from .env.example copies.
  if [[ -n "$saved_user" && "$saved_user" != *"example.com"* && "$saved_user" != your-wp-* ]]; then
    WP_USER="$saved_user"
  fi
}

verify_credentials() {
  local username="$1"
  local app_password="$2"
  local url="${LOCAL_WP_URL%/}/wp-json/complex-patient/v1/auth/exchange"
  local compact_password="${app_password// /}"
  local body http_code response

  if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 required for credential verification." >&2
    return 1
  fi

  body="$(python3 -c 'import json, sys; print(json.dumps({"username": sys.argv[1], "application_password": sys.argv[2]}))' \
    "$username" "$compact_password")"
  response="$(curl -sS -w $'\n__HTTP_CODE__:%{http_code}' \
    -X POST \
    -H "Content-Type: application/json" \
    -d "$body" \
    "$url" 2>/dev/null || true)"

  http_code="${response##*__HTTP_CODE__:}"
  response="${response%__HTTP_CODE__:*}"

  if [[ "$http_code" == "200" ]]; then
    echo "✓ Auth exchange OK (${url})"
    return 0
  fi

  echo "✗ Auth exchange failed (HTTP ${http_code}) at ${url}" >&2
  if [[ -n "$response" ]]; then
    echo "  Response: ${response}" >&2
  fi
  echo "  Is WordPress Studio running on ${LOCAL_WP_URL}? Try: studio site start --path \"${STUDIO_SITE_PATH}\"" >&2
  echo "  Is the plugin synced? Run from repo root: yarn sync:plugin-local" >&2
  return 1
}

write_env_file() {
  local username="$1"
  local app_password="$2"
  mkdir -p "$(dirname "$ENV_FILE")"
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/maestro-provision-wp-user.sh — do not commit (gitignored).
# WordPress Studio site: ${STUDIO_SITE_PATH}
# Sync backend: ${LOCAL_WP_URL}

MAESTRO_WP_USERNAME=${username}
MAESTRO_WP_PASSWORD=${app_password}
MAESTRO_VAULT_PASSPHRASE=${DEFAULT_VAULT_PASSPHRASE}
MAESTRO_BIRTH_MONTH=${BIRTH_MONTH}
MAESTRO_BIRTH_YEAR=${BIRTH_YEAR}
EOF
  chmod 600 "$ENV_FILE" 2>/dev/null || true
  echo "Wrote ${ENV_FILE}"
}

load_existing_env

if $VERIFY_ONLY; then
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Missing ${ENV_FILE}. Run: yarn maestro:provision" >&2
    exit 1
  fi
  WP_USER="$(read_env_value MAESTRO_WP_USERNAME "$ENV_FILE")"
  APP_PASS="$(read_env_value MAESTRO_WP_PASSWORD "$ENV_FILE")"
  [[ -n "$WP_USER" && -n "$APP_PASS" ]] || {
    echo "Incomplete ${ENV_FILE} (need MAESTRO_WP_USERNAME and MAESTRO_WP_PASSWORD)." >&2
    exit 1
  }
  verify_credentials "$WP_USER" "$APP_PASS"
  exit 0
fi

if ! command -v studio >/dev/null 2>&1; then
  echo "WordPress Studio CLI not found." >&2
  echo "Install Studio and enable CLI, or: npm install -g wp-studio" >&2
  echo "Docs: https://developer.wordpress.com/docs/developer-tools/studio/cli/" >&2
  exit 1
fi

if [[ ! -d "$STUDIO_SITE_PATH" ]]; then
  echo "Studio site path not found: ${STUDIO_SITE_PATH}" >&2
  echo "Set COMPLEX_PATIENT_STUDIO_SITE_PATH to your local site root." >&2
  exit 1
fi

echo "Studio site: ${STUDIO_SITE_PATH}"
echo "Maestro WP user: ${WP_USER}"

# Best-effort start (no-op if already running).
studio site start --path "$STUDIO_SITE_PATH" >/dev/null 2>&1 || true

if ! studio wp core is-installed --path "$STUDIO_SITE_PATH" >/dev/null 2>&1; then
  echo "WordPress is not installed at ${STUDIO_SITE_PATH}." >&2
  exit 1
fi

if studio wp user get "$WP_USER" --path="$STUDIO_SITE_PATH" >/dev/null 2>&1; then
  echo "User exists: ${WP_USER}"
else
  echo "Creating user ${WP_USER}…"
  studio wp user create "$WP_USER" "${WP_USER}@maestro.local" \
    --role=subscriber \
    --user_pass="$(openssl rand -base64 24)" \
    --path="$STUDIO_SITE_PATH"
fi

echo "Rotating application password \"${APP_PASSWORD_NAME}\"…"
while IFS= read -r uuid; do
  [[ -z "$uuid" ]] && continue
  studio wp user application-password delete "$WP_USER" "$uuid" --path="$STUDIO_SITE_PATH" >/dev/null 2>&1
done < <(
  studio wp user application-password list "$WP_USER" \
    --fields=uuid,name \
    --format=csv \
    --path="$STUDIO_SITE_PATH" \
    | tail -n +2 \
    | while IFS=',' read -r uuid name; do
        name="${name//\"/}"
        if [[ "$name" == "$APP_PASSWORD_NAME" ]]; then
          echo "$uuid"
        fi
      done
)

APP_PASS="$(
  studio wp user application-password create "$WP_USER" "$APP_PASSWORD_NAME" \
    --porcelain \
    --path="$STUDIO_SITE_PATH" 2>&1 \
    | grep -Eo '[A-Za-z0-9]{24}' \
    | tail -n 1
)"

if [[ -z "$APP_PASS" ]]; then
  echo "Failed to create application password." >&2
  exit 1
fi

write_env_file "$WP_USER" "$APP_PASS"

if ! $NO_VERIFY; then
  verify_credentials "$WP_USER" "$APP_PASS"
fi

echo ""
echo "Next steps:"
echo "  1. Dev build on simulator: cd expo && npx expo run:ios"
echo "  2. Smoke test:             cd expo && yarn test:maestro:smoke"
echo "  3. First unlock uses MAESTRO_VAULT_PASSPHRASE from .maestro/.env"
